import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const dist=path.resolve('dist/assets');const files=fs.readdirSync(dist);
const entry=files.find(f=>/^index-.*\.js$/.test(f));
assert.ok(entry);const size=fs.statSync(path.join(dist,entry)).size;
assert.ok(size<350000,'主入口超过 350KB: '+size);
const details=files.filter(f=>/^episodeDetail\d\d-.*\.js$/.test(f));
assert.equal(details.length,11,'必须有 11 个单作品懒加载 JS 模块');
assert.ok(details.every(f=>fs.statSync(path.join(dist,f)).size<100000),'单作品历史证据模块必须小于 100KB');
const source=fs.readFileSync('dist/index.html','utf8');
assert.ok(!/episodeDetail\d\d-.*\.js/.test(source),'首页 HTML 不应预加载全部历史详情');
console.log('PASS 11/11 Episode 详情分包按需加载；入口 '+size+' B；最大 Episode 详情 '+Math.max(...details.map(f=>fs.statSync(path.join(dist,f)).size))+' B');
const runs=files.filter(f=>/^runDetail\d\d-.*\.js$/.test(f));
assert.equal(runs.length,11,'必须有 11 个按需下载的 Run 历史详情 JS 模块');
assert.ok(runs.every(f=>fs.statSync(path.join(dist,f)).size<100000),'Run 详情模块必须小于 100KB');
assert.ok(!files.some(f=>/^historical-runs-.*\.js$/.test(f)),'不应保留 376KB 的历史 Run 整包');
assert.ok(!/runDetail\d\d-.*\.js/.test(source),'首页 HTML 不可提前加载所有 Run 详情');
console.log('PASS 11/11 Run 详情独立分包；最大 Run 详情 '+Math.max(...runs.map(f=>fs.statSync(path.join(dist,f)).size))+' B');
