import { StoryRunItem } from './types';

export const MOCK_STORY_RUNS: StoryRunItem[] = [
  {
    id: 'run-1',
    storyName: '尸解仙',
    runId: 'RUN-20260916-001',
    currentStage: 'PRODUCTION',
    stageLabel: 'Production',
    status: 'RUNNING',
    progressPercent: 68,
    completedFrames: 14,
    totalFrames: 20,
    currentAction: 'Frame14 · IMAGE_GENERATION',
    createdAt: '2025-06-19 10:23',
    duration: '28m',
    lastHeartbeatAgo: '3 秒前',
    heartbeatSeconds: 3,
    exceptionSummary: '-',
    exceptionType: 'none',
    storyDescription: '道士白玉楼勘破成仙秘辛，古道枯松下浮现诡谲肉身蜕变。',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    pipelineStages: [
      {
        key: 'CREATE',
        label: 'Create',
        status: 'completed',
        timeCost: '1m',
        startTime: '10:23:00',
        endTime: '10:24:00',
        attempt: '1/1',
        description: '故事种子初始化，生成世界观与基础结构元数据。',
        inputArtifacts: ['story_seed_prompt.txt'],
        outputArtifacts: ['story_manifest.json'],
        traceId: 'TR-STG-CREATE-001'
      },
      {
        key: 'STORY_LOCK',
        label: 'Story Lock',
        status: 'completed',
        timeCost: '4m',
        startTime: '10:24:00',
        endTime: '10:28:00',
        attempt: '1/1',
        description: '大纲与节拍表语义锁定，消除情节逻辑漏洞。',
        inputArtifacts: ['story_manifest.json'],
        outputArtifacts: ['locked_script_v1.json', 'narrative_beats.md'],
        traceId: 'TR-STG-LOCK-002'
      },
      {
        key: 'STORYBOARD',
        label: 'Storyboard',
        status: 'completed',
        timeCost: '8m',
        startTime: '10:28:00',
        endTime: '10:36:00',
        attempt: '1/1',
        description: '20 镜分镜台本切分、机位与运镜角度指令编译。',
        inputArtifacts: ['locked_script_v1.json'],
        outputArtifacts: ['storyboard_20frames.json'],
        traceId: 'TR-STG-STORYBD-003'
      },
      {
        key: 'CHARACTER_CONTRACT',
        label: 'Character Contract',
        status: 'completed',
        timeCost: '3m',
        startTime: '10:36:00',
        endTime: '10:39:00',
        attempt: '1/1',
        description: '白玉楼、蛇蜕道尊等核心角色三视图与视觉特征向量绑定。',
        inputArtifacts: ['storyboard_20frames.json'],
        outputArtifacts: ['character_contracts.json', 'p01_seed_refs.png'],
        traceId: 'TR-STG-CHAR-004'
      },
      {
        key: 'VISUAL_LOCK',
        label: 'Visual Lock',
        status: 'completed',
        timeCost: '6m',
        startTime: '10:39:00',
        endTime: '10:45:00',
        attempt: '1/1',
        description: '色调与美术风格锚定：阴郁水墨+雨夜冷光+古铜暖光对比。',
        inputArtifacts: ['character_contracts.json'],
        outputArtifacts: ['style_anchor_palette.json', 'keyframe_refs.zip'],
        traceId: 'TR-STG-VISLOCK-005'
      },
      {
        key: 'PRODUCTION',
        label: 'Production',
        status: 'running',
        timeCost: '28m (进行中)',
        startTime: '10:45:00',
        endTime: '-',
        attempt: '2/3',
        description: '分布式并行渲染 20 个高保真分镜，当前已完成 14 帧。',
        inputArtifacts: ['storyboard_20frames.json', 'style_anchor_palette.json'],
        outputArtifacts: ['frame_01_14_artifacts.zip'],
        traceId: 'TR-STG-PROD-006'
      },
      {
        key: 'REVIEW',
        label: 'Review',
        status: 'pending',
        timeCost: '未开始',
        description: '自动一致性校验与人工双重定帧审核。',
        inputArtifacts: ['all_20_frames.zip'],
        traceId: 'TR-STG-REV-007'
      },
      {
        key: 'PUBLISH',
        label: 'Publish',
        status: 'pending',
        timeCost: '未开始',
        description: '多平台规格打包、音效对齐与一键交付。',
        traceId: 'TR-STG-PUB-008'
      },
    ],
    events: [
      { id: 'ev-1', timestamp: '10:23:00', stage: 'CREATE', eventName: 'RUN_INITIALIZED', status: 'info', detail: 'StoryOS 调度器派发任务，分配至集群 Worker-01' },
      { id: 'ev-2', timestamp: '10:24:00', stage: 'STORY_LOCK', eventName: 'SCRIPT_LOCKED', status: 'success', detail: '大纲与节拍通过一致性核验，锁定 20 个剧情节拍点' },
      { id: 'ev-3', timestamp: '10:28:00', stage: 'STORYBOARD', eventName: 'STORYBOARD_COMPILED', status: 'success', detail: '20 镜分镜台本与相机景别指令编译完毕' },
      { id: 'ev-4', timestamp: '10:36:00', stage: 'CHARACTER_CONTRACT', eventName: 'CONTRACT_VALIDATED', status: 'success', detail: '角色白玉楼面部一致性契约锁定，特征向量注入成功' },
      { id: 'ev-5', timestamp: '10:39:00', stage: 'VISUAL_LOCK', eventName: 'PALETTE_LOCKED', status: 'success', detail: '雨夜古风暗黑水墨调色盘完成锚定' },
      { id: 'ev-6', timestamp: '10:45:00', stage: 'PRODUCTION', eventName: 'BATCH_DISPATCH', status: 'info', detail: '20 个分镜渲染任务批量入队，Worker-01 开始拉取首批' },
      { id: 'ev-7', timestamp: '10:52:10', stage: 'PRODUCTION', eventName: 'FRAME_SUCCESS', status: 'success', detail: 'Frame 01 ~ Frame 08 批量渲染完成并写入对象存储' },
      { id: 'ev-8', timestamp: '11:18:22', stage: 'PRODUCTION', eventName: 'FRAME_ERROR', status: 'error', detail: 'Frame 09 渲染发生 NETWORK_ERROR (Upstream Model API Timeout 60s)' },
      { id: 'ev-9', timestamp: '11:18:25', stage: 'PRODUCTION', eventName: 'RETRY_SCHEDULED', status: 'warn', detail: '指数退避重试机制触发，计划 17s 后自动发起 Attempt 2/3' },
      { id: 'ev-10', timestamp: '11:18:42', stage: 'PRODUCTION', eventName: 'FRAME_RETRY_STARTED', status: 'info', detail: 'Frame 09 Attempt 2/3 重新连入推理通道' },
      { id: 'ev-11', timestamp: '11:21:05', stage: 'PRODUCTION', eventName: 'HEARTBEAT_ACK', status: 'info', detail: 'Worker-01 汇报健康心跳，GPU 显存占用 68%，温度 59°C' },
    ],
    artifacts: [
      { id: 'art-1', name: 'storyboard_manifest.json', stage: 'STORYBOARD', fileType: 'json', size: '124 KB', updatedAt: '10:36:00', previewSnippet: '{\n  "totalFrames": 20,\n  "aspectRatio": "4:5",\n  "colorGrade": "dark_cinematic_ink"\n}' },
      { id: 'art-2', name: 'character_contract_baiyulou.json', stage: 'CHARACTER_CONTRACT', fileType: 'json', size: '86 KB', updatedAt: '10:39:00', previewSnippet: '{\n  "character": "白玉楼",\n  "hair": "道髻散乱半披肩",\n  "garment": "破损青布道袍"\n}' },
      { id: 'art-3', name: 'style_anchor_reference_pack.zip', stage: 'VISUAL_LOCK', fileType: 'archive', size: '4.8 MB', updatedAt: '10:45:00' },
      { id: 'art-4', name: 'frames_01_to_08_render.zip', stage: 'PRODUCTION', fileType: 'archive', size: '38.2 MB', updatedAt: '10:52:10' },
      { id: 'art-5', name: 'production_audit_trace.json', stage: 'PRODUCTION', fileType: 'json', size: '45 KB', updatedAt: '11:18:42' },
    ],
    logs: [
      { id: 'lg-1', timestamp: '11:18:15', level: 'INFO', component: 'BatchDispatcher', message: 'Worker-01: Dispatched Frame 09 payload with references [P01, P02_face]' },
      { id: 'lg-2', timestamp: '11:18:22', level: 'ERROR', component: 'ModelConnector', message: 'Inference gateway socket hangup while waiting for upstream response (Timeout 60s)', traceId: 'TR-20260916-09F-A882' },
      { id: 'lg-3', timestamp: '11:18:25', level: 'WARN', component: 'ResilienceEngine', message: 'Auto-recovery policy matched: NETWORK_ERROR. Scheduling exponential backoff retry in 17s.' },
      { id: 'lg-4', timestamp: '11:18:42', level: 'INFO', component: 'BatchDispatcher', message: 'Worker-01: Initiating Frame 09 Attempt 2/3 with warm connection pool.' },
      { id: 'lg-5', timestamp: '11:20:10', level: 'DEBUG', component: 'HeartbeatService', message: 'Worker-01 pulse received. Memory 4.1GB/16GB, GPU Util 74%.' },
      { id: 'lg-6', timestamp: '11:21:00', level: 'INFO', component: 'ProductionMonitor', message: 'Frame 14 rendering progress: Step 28/35 (Latent diffusion denoising).' },
    ],
    runtimeEnv: {
      workerId: 'worker-node-01-eu',
      gpuNode: 'NVIDIA A100-SXM4-80GB (Node-Pool-East)',
      modelProvider: 'gpt-image-2.5-flare (Enterprise Engine)',
      imageResolution: '1080 × 1350 px (Cinematic 4:5)',
      aspectRatio: '4:5 Vertical Stills',
      heartbeatInterval: '5000 ms (Strict WebSocket Keepalive)',
      activeConcurrency: '4 Workers / Pool 01',
    },
    frames: [
      { frameNo: 1, frameCode: 'Frame 01', status: 'PASSED', attempt: '1/1', thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=300&q=80', duration: '32s', provider: 'gpt-image-2.5-flare' },
      { frameNo: 2, frameCode: 'Frame 02', status: 'PASSED', attempt: '1/1', thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=300&q=80', duration: '35s', provider: 'gpt-image-2.5-flare' },
      { frameNo: 3, frameCode: 'Frame 03', status: 'PASSED', attempt: '1/1', thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=300&q=80', duration: '29s', provider: 'gpt-image-2.5-flare' },
      { frameNo: 4, frameCode: 'Frame 04', status: 'PASSED', attempt: '1/1', thumbnail: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=300&q=80', duration: '38s', provider: 'gpt-image-2.5-flare' },
      { frameNo: 5, frameCode: 'Frame 05', status: 'PASSED', attempt: '1/1', thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=300&q=80', duration: '31s', provider: 'gpt-image-2.5-flare' },
      { frameNo: 6, frameCode: 'Frame 06', status: 'PASSED', attempt: '1/1', thumbnail: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=300&q=80', duration: '41s', provider: 'gpt-image-2.5-flare' },
      { frameNo: 7, frameCode: 'Frame 07', status: 'PASSED', attempt: '1/1', thumbnail: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=300&q=80', duration: '30s', provider: 'gpt-image-2.5-flare' },
      {
        frameNo: 8,
        frameCode: 'Frame 08',
        status: 'PASSED',
        attempt: '1 / 1',
        completedAt: '10:31:44',
        thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
        duration: '33s',
        provider: 'gpt-image-2.5-flare',
        modelName: 'dall-e-3-turbo-v2',
        references: ['P01', 'P02_face'],
        referenceItems: [
          { name: 'P01', type: 'scene', url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=240&q=80' },
          { name: 'P02_face', type: 'character', url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=240&q=80' }
        ],
        prompt: '道士白玉楼手扶枯松，冷风掠起残破道袍，眼眸泛着幽微荧光，4:5 电影级水墨冷光，景别：中景，8k 原生渲染。',
        artifactName: 'frame_08.png',
        artifactSize: '4.2 MB',
        artifactUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
        traceId: 'TR-IMG-PROD-08-9941A'
      },
      {
        frameNo: 9,
        frameCode: 'Frame 09',
        status: 'RETRYING',
        attempt: '2 / 3',
        lastError: 'NETWORK_ERROR',
        failureStage: 'provider_download',
        failedAt: '11:18:22',
        nextRetryInSeconds: 17,
        duration: '48s',
        provider: 'gpt-image-2.5-flare',
        modelName: 'flux-cinematic-pro',
        references: ['P01', 'P02_face'],
        referenceItems: [
          { name: 'P01', type: 'scene', url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=240&q=80' },
          { name: 'P02_face', type: 'character', url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=240&q=80' }
        ],
        prompt: '雨夜古道悬崖，道长白玉楼青袍残破，手持滴血桃木剑，背后闪电破空照亮巨蛇古铜鳞片。景别：过肩全景，4:5 竖构图，电影级体积光。',
        artifactName: 'frame_09_temp.part',
        artifactSize: '1.8 MB',
        artifactUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
        traceId: 'TR-20260916-09F-A882',
        recentEvents: [
          { time: '11:18:22', text: '生成失败 · NETWORK_ERROR (Socket Timeout 60s)', type: 'error' },
          { time: '11:18:25', text: '进入退避队列 (17s 后自动触发 Attempt 2/3)', type: 'schedule' },
          { time: '11:18:42', text: '重试开始 Attempt 2/3 · 重新建立连接', type: 'start' },
          { time: '11:19:15', text: '正在进行第二阶段高保真渲染...', type: 'start' },
        ]
      },
      { frameNo: 10, frameCode: 'Frame 10', status: 'QUEUED', attempt: '0 / 3', duration: '等待中' },
      { frameNo: 11, frameCode: 'Frame 11', status: 'QUEUED', attempt: '0 / 3', duration: '等待中' },
      { frameNo: 12, frameCode: 'Frame 12', status: 'QUEUED', attempt: '0 / 3', duration: '等待中' },
      { frameNo: 13, frameCode: 'Frame 13', status: 'QUEUED', attempt: '0 / 3', duration: '等待中' },
      {
        frameNo: 14,
        frameCode: 'Frame 14',
        status: 'GENERATING',
        currentSubAction: 'IMAGE_GENERATION',
        attempt: '1 / 3',
        duration: '14s',
        provider: 'gpt-image-2.5-flare',
        modelName: 'flux-cinematic-pro',
        references: ['P01', 'P02_face'],
        prompt: '蛇蜕暗洞深处，古铜灯盏微明，地面散落半截蜕皮与古道符咒。景别：特写仰角，冷绿荧光，浅景深。',
        traceId: 'TR-20260916-14F-B031',
        recentEvents: [
          { time: '11:20:50', text: 'Compile Prompt 完成', type: 'start' },
          { time: '11:20:54', text: 'Resolve References 契约校验通过', type: 'start' },
          { time: '11:20:58', text: 'Submit Provider 派发成功', type: 'start' },
          { time: '11:21:00', text: 'Generating · 潜空间去噪 Step 28/35', type: 'start' },
        ]
      },
      { frameNo: 15, frameCode: 'Frame 15', status: 'NOT_STARTED', attempt: '0 / 3' },
      { frameNo: 16, frameCode: 'Frame 16', status: 'NOT_STARTED', attempt: '0 / 3' },
      { frameNo: 17, frameCode: 'Frame 17', status: 'NOT_STARTED', attempt: '0 / 3' },
      { frameNo: 18, frameCode: 'Frame 18', status: 'NOT_STARTED', attempt: '0 / 3' },
      { frameNo: 19, frameCode: 'Frame 19', status: 'NOT_STARTED', attempt: '0 / 3' },
      { frameNo: 20, frameCode: 'Frame 20', status: 'NOT_STARTED', attempt: '0 / 3' },
    ]
  },
  {
    id: 'run-2',
    storyName: '天界普通女人',
    runId: 'RUN-20260916-002',
    currentStage: 'REVIEW',
    stageLabel: 'Review',
    status: 'RUNNING',
    progressPercent: 92,
    completedFrames: 20,
    totalFrames: 20,
    currentAction: '内容审核',
    createdAt: '2025-06-19 09:12',
    duration: '46m',
    lastHeartbeatAgo: '2 秒前',
    heartbeatSeconds: 2,
    exceptionSummary: '-',
    exceptionType: 'none',
    storyDescription: '九天玄阁小仙官的打工日记，天界神力与世俗烟火的欢脱碰撞。',
    coverImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    pipelineStages: [
      { key: 'CREATE', label: 'Create', status: 'completed', timeCost: '1m' },
      { key: 'STORY_LOCK', label: 'Story Lock', status: 'completed', timeCost: '3m' },
      { key: 'STORYBOARD', label: 'Storyboard', status: 'completed', timeCost: '6m' },
      { key: 'CHARACTER_CONTRACT', label: 'Character Contract', status: 'completed', timeCost: '4m' },
      { key: 'VISUAL_LOCK', label: 'Visual Lock', status: 'completed', timeCost: '5m' },
      { key: 'PRODUCTION', label: 'Production', status: 'completed', timeCost: '22m' },
      { key: 'REVIEW', label: 'Review', status: 'running', timeCost: '5m' },
      { key: 'PUBLISH', label: 'Publish', status: 'pending' },
    ],
    frames: Array.from({ length: 20 }, (_, i) => ({
      frameNo: i + 1,
      frameCode: `Frame ${String(i + 1).padStart(2, '0')}`,
      status: 'PASSED' as const,
      thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=300&q=80',
      duration: '34s',
      attempt: '1/1',
      provider: 'gpt-image-2.5-flare'
    }))
  },
  {
    id: 'run-3',
    storyName: '江南普通人的一天',
    runId: 'RUN-20260916-003',
    currentStage: 'PRODUCTION',
    stageLabel: 'Production',
    status: 'BLOCKED',
    progressPercent: 54,
    completedFrames: 9,
    totalFrames: 20,
    currentAction: '图像生成',
    createdAt: '2025-06-19 08:41',
    duration: '31m',
    lastHeartbeatAgo: '8 秒前',
    heartbeatSeconds: 8,
    exceptionSummary: 'Network Error',
    exceptionType: 'manual',
    storyDescription: '晨起乌篷船，姑苏城外枫桥夜泊，小巷茶肆里的市井浮生。',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    pipelineStages: [
      { key: 'CREATE', label: 'Create', status: 'completed', timeCost: '1m' },
      { key: 'STORY_LOCK', label: 'Story Lock', status: 'completed', timeCost: '2m' },
      { key: 'STORYBOARD', label: 'Storyboard', status: 'completed', timeCost: '5m' },
      { key: 'CHARACTER_CONTRACT', label: 'Character Contract', status: 'completed', timeCost: '3m' },
      { key: 'VISUAL_LOCK', label: 'Visual Lock', status: 'completed', timeCost: '4m' },
      { key: 'PRODUCTION', label: 'Production', status: 'warning', timeCost: '16m' },
      { key: 'REVIEW', label: 'Review', status: 'pending' },
      { key: 'PUBLISH', label: 'Publish', status: 'pending' },
    ],
    frames: Array.from({ length: 20 }, (_, i) => {
      const fn = i + 1;
      return {
        frameNo: fn,
        frameCode: `Frame ${String(fn).padStart(2, '0')}`,
        status: fn <= 8 ? 'PASSED' : fn === 9 ? 'BLOCKED' : fn <= 12 ? 'QUEUED' : 'NOT_STARTED',
        thumbnail: fn <= 8 ? 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=300&q=80' : undefined,
        duration: fn <= 8 ? '31s' : fn === 9 ? '已阻塞' : '待处理',
        attempt: fn === 9 ? '3 / 3' : '1/1',
        lastError: fn === 9 ? 'Reference Missing: P02_face 不存在' : undefined,
        provider: 'gpt-image-2.5-flare'
      };
    })
  },
  {
    id: 'run-4',
    storyName: '照片里的那个人',
    runId: 'RUN-20260916-004',
    currentStage: 'VISUAL_LOCK',
    stageLabel: 'Visual Lock',
    status: 'WAITING',
    waitingReason: '等待模型',
    progressPercent: 37,
    completedFrames: 0,
    totalFrames: 20,
    currentAction: 'Reference 校验',
    createdAt: '2025-06-19 11:02',
    duration: '8m',
    lastHeartbeatAgo: '1 秒前',
    heartbeatSeconds: 1,
    exceptionSummary: '等待模型',
    exceptionType: 'none',
    storyDescription: '一张泛黄黑白合影，背后暗藏三十年跨越时空的记忆重构。',
    coverImage: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=600&q=80',
    pipelineStages: [
      { key: 'CREATE', label: 'Create', status: 'completed', timeCost: '1m' },
      { key: 'STORY_LOCK', label: 'Story Lock', status: 'completed', timeCost: '2m' },
      { key: 'STORYBOARD', label: 'Storyboard', status: 'completed', timeCost: '3m' },
      { key: 'CHARACTER_CONTRACT', label: 'Character Contract', status: 'completed', timeCost: '2m' },
      { key: 'VISUAL_LOCK', label: 'Visual Lock', status: 'running', timeCost: '等待模型' },
      { key: 'PRODUCTION', label: 'Production', status: 'pending' },
      { key: 'REVIEW', label: 'Review', status: 'pending' },
      { key: 'PUBLISH', label: 'Publish', status: 'pending' },
    ],
    frames: Array.from({ length: 20 }, (_, i) => ({
      frameNo: i + 1,
      frameCode: `Frame ${String(i + 1).padStart(2, '0')}`,
      status: 'NOT_STARTED' as const,
      attempt: '0/3'
    }))
  },
  {
    id: 'run-5',
    storyName: '婚礼前夜',
    runId: 'RUN-20260916-005',
    currentStage: 'COMPLETED',
    stageLabel: 'Completed',
    status: 'COMPLETED',
    progressPercent: 100,
    completedFrames: 20,
    totalFrames: 20,
    currentAction: '发布就绪',
    createdAt: '2025-06-18 16:20',
    duration: '1h12m',
    lastHeartbeatAgo: '已归档',
    heartbeatSeconds: 0,
    exceptionSummary: '-',
    exceptionType: 'none',
    storyDescription: '悬疑反转都市情感剧，红毯前的最后一次抉择与真相揭开。',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    pipelineStages: [
      { key: 'CREATE', label: 'Create', status: 'completed', timeCost: '2m' },
      { key: 'STORY_LOCK', label: 'Story Lock', status: 'completed', timeCost: '5m' },
      { key: 'STORYBOARD', label: 'Storyboard', status: 'completed', timeCost: '7m' },
      { key: 'CHARACTER_CONTRACT', label: 'Character Contract', status: 'completed', timeCost: '4m' },
      { key: 'VISUAL_LOCK', label: 'Visual Lock', status: 'completed', timeCost: '6m' },
      { key: 'PRODUCTION', label: 'Production', status: 'completed', timeCost: '35m' },
      { key: 'REVIEW', label: 'Review', status: 'completed', timeCost: '8m' },
      { key: 'PUBLISH', label: 'Publish', status: 'completed', timeCost: '5m' },
    ],
    frames: Array.from({ length: 20 }, (_, i) => ({
      frameNo: i + 1,
      frameCode: `Frame ${String(i + 1).padStart(2, '0')}`,
      status: 'PASSED' as const,
      thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=300&q=80',
      duration: '36s',
      attempt: '1/1',
      provider: 'gpt-image-2.5-flare'
    }))
  },
  {
    id: 'run-6',
    storyName: '彼此天空 EP004',
    runId: 'RUN-20260916-006',
    currentStage: 'STORYBOARD',
    stageLabel: 'Storyboard',
    status: 'RUNNING',
    progressPercent: 41,
    completedFrames: 3,
    totalFrames: 20,
    currentAction: '生成分镜',
    createdAt: '2025-06-19 10:55',
    duration: '18m',
    lastHeartbeatAgo: '5 秒前',
    heartbeatSeconds: 5,
    exceptionSummary: '-',
    exceptionType: 'none',
    storyDescription: '科幻双子星纪元，两个不同引力维度的平行时空对话。',
    coverImage: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=600&q=80',
    pipelineStages: [
      { key: 'CREATE', label: 'Create', status: 'completed', timeCost: '1m' },
      { key: 'STORY_LOCK', label: 'Story Lock', status: 'completed', timeCost: '4m' },
      { key: 'STORYBOARD', label: 'Storyboard', status: 'running', timeCost: '13m' },
      { key: 'CHARACTER_CONTRACT', label: 'Character Contract', status: 'pending' },
      { key: 'VISUAL_LOCK', label: 'Visual Lock', status: 'pending' },
      { key: 'PRODUCTION', label: 'Production', status: 'pending' },
      { key: 'REVIEW', label: 'Review', status: 'pending' },
      { key: 'PUBLISH', label: 'Publish', status: 'pending' },
    ],
    frames: Array.from({ length: 20 }, (_, i) => {
      const fn = i + 1;
      return {
        frameNo: fn,
        frameCode: `Frame ${String(fn).padStart(2, '0')}`,
        status: fn <= 3 ? 'PASSED' : fn === 4 ? 'GENERATING' : fn <= 7 ? 'QUEUED' : 'NOT_STARTED',
        thumbnail: fn <= 3 ? 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=300&q=80' : undefined,
        duration: fn <= 3 ? '32s' : '排队中',
        attempt: '1/1',
        provider: 'gpt-image-2.5-flare'
      };
    })
  }
];

export const MOCK_MONITOR_METRICS = {
  totalStories: 12,
  runningStories: 4,
  waitingStories: 2,
  blockedStories: 1,
  failedStories: 0,
  todayCompletedStories: 18,
  activeWorkers: [
    { id: 'Worker-01', status: 'running', storyName: '尸解仙', currentFrame: 'Frame08' },
    { id: 'Worker-02', status: 'running', storyName: '天界女人', currentFrame: 'Frame19' },
    { id: 'Worker-03', status: 'running', storyName: '江南生活', currentFrame: 'Frame09' },
    { id: 'Worker-04', status: 'running', storyName: '彼此天空', currentFrame: 'Frame02' },
  ],
  queueStats: {
    totalWaiting: 26,
    generating: 4,
    queued: 18,
    retrying: 2,
    other: 2,
  },
  exceptionStats: {
    manualActionRequired: 1,
    autoRecovering: 3,
  },
  recentEvents: [
    { time: '11:23', story: '尸解仙', text: 'Frame14 生成开始', type: 'start' },
    { time: '11:25', story: '江南生活', text: 'Frame09 重试中', type: 'retry' },
    { time: '11:20', story: '天界女人', text: 'Frame19 生成完成', type: 'success' },
    { time: '11:18', story: '照片里的那个人', text: 'Reference 校验等待', type: 'waiting' },
  ],
  runtimeHealth: {
    redis: '正常',
    mysql: '正常',
    imageApi: '正常',
    workerStatus: '4 / 4',
    queueTotal: 26
  }
};
