import { Episode } from './types';

// Web Console 前端示例数据集；仅用于 UI 演示，不是 Episode Authority，也不代表真实生产状态。
export const MOCK_EPISODES: Episode[] = [
  {
    id: 'ep-04-fogvilla',
    code: 'EP-04',
    title: '白雾山庄惨案',
    synopsis: '雨夜封山的白雾山庄内，一名客人离奇失踪，现场仅留下一张带着血迹的 4:5 拍立得照片。',
    genre: '悬疑推理 / 暴风雪山庄',
    totalFrames: 32,
    completedFrames: 24,
    currentStage: 'PRODUCTION_PASSED',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    updatedAt: '刚刚',
    runtimeRequest: {
      imageModel: 'gpt-image-2',
      quality: 'high',
      aspectRatio: '4:5 1080×1350',
      batchMode: '5 帧逻辑批次',
      maxConcurrentImages: 3,
      executionLayer: 'StoryOS Engine',
      sourceBadge: '示例数据',
    },
    currentBatch: {
      batchId: 'batch-04',
      batchNumber: 4,
      batchName: '逻辑批次 #04 (雨夜长廊探索)',
      targetFrames: 'Frame #16 - #20',
      totalImages: 5,
      createdAt: '14:55',
      status: 'ready_for_review',
      items: [
        {
          id: 'b4-f16',
          frameIndex: 16,
          prompt: '林澈手持电筒推开老旧木门，光束穿过空气中的浮尘',
          seed: 4892011,
          status: 'qa_passed',
          progress: 100,
          renderTime: '2.1s',
          imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.98,
        },
        {
          id: 'b4-f17',
          frameIndex: 17,
          prompt: '地板上的水渍延伸向走廊尽头，特写脚印倒影',
          seed: 4892012,
          status: 'qa_passed',
          progress: 100,
          renderTime: '1.9s',
          imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.97,
        },
        {
          id: 'b4-f18',
          frameIndex: 18,
          prompt: '窗玻璃上的雨珠映出虚幻人影，局部重影微调',
          seed: 4892013,
          status: 'qa_warning',
          progress: 100,
          renderTime: '2.4s',
          imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.91,
          driftWarning: '玻璃倒影轻微双重重影，建议使用 Inpaint 修复',
        },
        {
          id: 'b4-f19',
          frameIndex: 19,
          prompt: '墙上的鹿头挂件斜垂，影子被电筒拉长',
          seed: 4892014,
          status: 'qa_passed',
          progress: 100,
          renderTime: '1.8s',
          imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.99,
        },
        {
          id: 'b4-f20',
          frameIndex: 20,
          prompt: '林澈驻足在紧锁的 302 房门前，神情警惕',
          seed: 4892015,
          status: 'qa_passed',
          progress: 100,
          renderTime: '2.0s',
          imageUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.97,
        },
      ],
    },
    frameReviews: [
      {
        frameId: 'FR-16',
        frameIndex: 16,
        timestamp: '14:56',
        imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
        shotType: '中景 / 4:5',
        facialScore: 0.98,
        lightConsistency: 0.97,
        anatomyScore: 0.99,
        verdict: 'PASS',
        issueTags: ['人脸基准符合'],
        reviewer: 'QualityGate',
        comment: '光影与人脸一致性优良',
      },
      {
        frameId: 'FR-18',
        frameIndex: 18,
        timestamp: '14:57',
        imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=400&q=80',
        shotType: '特写 / 4:5',
        facialScore: 0.92,
        lightConsistency: 0.94,
        anatomyScore: 0.96,
        verdict: 'WARN',
        issueTags: ['倒影轻微重影'],
        reviewer: 'QualityGate',
        comment: '倒影建议局部 Inpaint 修复',
      },
    ],
  },
  {
    id: 'ep-03-rainhunt',
    code: 'EP-03',
    title: '雨夜追凶 (全帧已交付)',
    synopsis: '林澈沿山脚泥泞车辙一路追踪黑色越野车，在废弃修车厂遭遇伏击，完成首轮证据提取。',
    genre: '警匪动作 / 硬汉推理',
    totalFrames: 32,
    completedFrames: 32,
    currentStage: 'PUBLISH_READY',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    updatedAt: '2小时前',
    runtimeRequest: {
      imageModel: 'gpt-image-2',
      quality: 'high',
      aspectRatio: '4:5 1080×1350',
      batchMode: '5 帧逻辑批次',
      maxConcurrentImages: 3,
      executionLayer: 'StoryOS Engine',
      sourceBadge: '示例数据',
    },
    currentBatch: {
      batchId: 'batch-06',
      batchNumber: 6,
      batchName: '交付批次 #06 (全量质检收敛)',
      targetFrames: 'Frame #28 - #32',
      totalImages: 5,
      createdAt: '11:20',
      status: 'completed',
      items: [
        {
          id: 'b6-f28',
          frameIndex: 28,
          prompt: '林澈在修车厂铁门前掏出战术手电，光斑映亮锈蚀把手',
          seed: 9182301,
          status: 'qa_passed',
          progress: 100,
          renderTime: '1.7s',
          imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.99,
        },
        {
          id: 'b6-f29',
          frameIndex: 29,
          prompt: '地面上未熄灭的烟头冒着白烟，雨水溅起微尘',
          seed: 9182302,
          status: 'qa_passed',
          progress: 100,
          renderTime: '1.9s',
          imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.98,
        },
      ],
    },
    frameReviews: [],
  },
  {
    id: 'ep-char-calibration',
    code: 'CHAR-01',
    title: '林澈角色基准与人脸校准',
    synopsis: '针对全季主角林澈的多角度光影一致性与眼神光锚定测试，固化 85mm 肖像核心权重向量。',
    genre: '角色设定 / 视觉资产工程',
    totalFrames: 16,
    completedFrames: 14,
    currentStage: 'VISUAL_CALIBRATED',
    coverImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    updatedAt: '昨天',
    runtimeRequest: {
      imageModel: 'gpt-image-2',
      quality: 'high',
      aspectRatio: '4:5 1080×1350',
      batchMode: '5 帧逻辑批次',
      maxConcurrentImages: 3,
      executionLayer: 'StoryOS Engine',
      sourceBadge: '示例数据',
    },
    currentBatch: {
      batchId: 'batch-c1',
      batchNumber: 1,
      batchName: '校准批次 #01 (三面图及侧光)',
      targetFrames: 'Frame #01 - #05',
      totalImages: 5,
      createdAt: '昨天',
      status: 'completed',
      items: [
        {
          id: 'bc1-f01',
          frameIndex: 1,
          prompt: '林澈正面肖像，冷光 85mm 景深，眼神锐利',
          seed: 1029381,
          status: 'qa_passed',
          progress: 100,
          renderTime: '2.0s',
          imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.995,
        },
      ],
    },
    frameReviews: [],
  },
  {
    id: 'series-02-abyss',
    code: 'SERIES-02',
    title: '深渊回响 · 科幻悬疑短剧',
    synopsis: '深海科考站接收到底层地幔传来的周期性莫尔斯电码，全体科研人员陷入认知错乱。',
    genre: '克苏鲁科幻 / 封闭密室',
    totalFrames: 28,
    completedFrames: 0,
    currentStage: 'IDEA_LOCKED',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    updatedAt: '3天前',
    runtimeRequest: {
      imageModel: 'gpt-image-2',
      quality: 'high',
      aspectRatio: '4:5 1080×1350',
      batchMode: '5 帧逻辑批次',
      maxConcurrentImages: 3,
      executionLayer: 'StoryOS Engine',
      sourceBadge: '示例数据',
    },
    currentBatch: {
      batchId: 'batch-abyss-01',
      batchNumber: 1,
      batchName: '概念预演批次',
      targetFrames: 'Frame #01 - #05',
      totalImages: 0,
      createdAt: '3天前',
      status: 'processing',
      items: [],
    },
    frameReviews: [],
  },
  {
    id: 'series-03-hotspring',
    code: 'SERIES-03',
    title: '废弃温泉镇 · 图文漫改',
    synopsis: '荒废三十年的温泉旅馆再次亮起灯火，相册里提前预演了次日受害者的死亡姿势。',
    genre: '中式微恐 / 规则怪谈',
    totalFrames: 30,
    completedFrames: 8,
    currentStage: 'STORYBOARD_LOCKED',
    coverImage: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
    updatedAt: '4天前',
    runtimeRequest: {
      imageModel: 'gpt-image-2',
      quality: 'high',
      aspectRatio: '4:5 1080×1350',
      batchMode: '5 帧逻辑批次',
      maxConcurrentImages: 3,
      executionLayer: 'StoryOS Engine',
      sourceBadge: '示例数据',
    },
    currentBatch: {
      batchId: 'batch-hs-02',
      batchNumber: 2,
      batchName: '分镜定稿批次',
      targetFrames: 'Frame #06 - #10',
      totalImages: 2,
      createdAt: '4天前',
      status: 'ready_for_review',
      items: [
        {
          id: 'bhs-f06',
          frameIndex: 6,
          prompt: '荒废旅馆大厅木柱上的日历停在 1994 年 11 月 14 日',
          seed: 4920192,
          status: 'qa_passed',
          progress: 100,
          renderTime: '1.9s',
          imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=400&q=80',
          consistencyScore: 0.98,
        },
      ],
    },
    frameReviews: [],
  },
  {
    id: 'series-04-neon',
    code: 'SERIES-04',
    title: '赛博霓虹档案 · 分镜剧场',
    synopsis: '新九龙地下第七层，记忆贩子截获了一段被加密的政客仿生记忆备份。',
    genre: '赛博朋克 / 硬核科幻',
    totalFrames: 30,
    completedFrames: 30,
    currentStage: 'PUBLISHED',
    coverImage: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80',
    updatedAt: '上周',
    runtimeRequest: {
      imageModel: 'gpt-image-2',
      quality: 'high',
      aspectRatio: '4:5 1080×1350',
      batchMode: '5 帧逻辑批次',
      maxConcurrentImages: 3,
      executionLayer: 'StoryOS Engine',
      sourceBadge: '示例数据',
    },
    currentBatch: {
      batchId: 'batch-neon-06',
      batchNumber: 6,
      batchName: '终审已发布批次',
      targetFrames: 'Frame #26 - #30',
      totalImages: 5,
      createdAt: '上周',
      status: 'completed',
      items: [],
    },
    frameReviews: [],
  },
];

export const SYSTEM_RUNTIME_LOGS = [
  { time: '14:55:02', level: 'INFO', module: 'Scheduler', message: 'StoryOS 引擎接收调度指令：批次出图 #04 (Frame 16-20)' },
  { time: '14:55:04', level: 'INFO', module: 'RuntimeRequest', message: '校验模型: gpt-image-2, quality: high, aspect: 4:5' },
  { time: '14:56:10', level: 'SUCCESS', module: 'QualityGate', message: 'Frame #16-#17 质检通过' },
  { time: '14:57:12', level: 'WARN', module: 'QualityGate', message: 'Frame #18 检测到倒影微瑕，建议 Inpaint 修复' },
];
