#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Import a real image generated by the WORK/WEB product runtime into Story OS.

This is a deterministic file adapter. It never invokes Codex or any model. The
surrounding product runtime generates the image, saves the RAW file, then calls
this importer to bind the file to the queued Frame Contract, Provider Receipt,
Raw Candidate Budget and Production Ledger.

V2.6.1.1 adds a fail-closed import transaction: after a budget claim, any
technical failure before candidate commit releases the claim, records ledger
TECH_FAIL, and moves the queue item out of running state. Once a normalized
candidate is committed, the content budget remains consumed even if later
ledger finalization fails, because a real content candidate already exists.
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from canvas_normalize import NormalizeError, normalize, read_canvas
import frame_contract
import image_model_policy
import image_scheduler
import provider_capability
import raw_candidate_budget
import runtime_router

ROOT = Path(__file__).resolve().parents[2]

PNG = b"\x89PNG\r\n\x1a\n"
JPEG = b"\xff\xd8\xff"


class ProductImageImportError(RuntimeError):
    pass


def valid_image(path: Path) -> bool:
    if not path.is_file() or path.stat().st_size < 16:
        return False
    header = path.read_bytes()[:16]
    return header.startswith(PNG) or header.startswith(JPEG)


def repo_rel(path: Path) -> str:
    return path.resolve().relative_to(ROOT.resolve()).as_posix()


def find_queue_item(ep: Path, frame: int, item_id: str | None) -> dict:
    q = image_scheduler.load_queue(ep)
    rows = [x for x in q.get("items") or [] if int(x.get("frame") or 0) == frame]
    if item_id:
        rows = [x for x in rows if str(x.get("id")) == item_id]
    rows = [x for x in rows if x.get("status") in {"queued", "running", "tech_failed"}]
    if not rows:
        raise ProductImageImportError(f"no importable queue item for frame {frame:02d}")
    rows.sort(key=lambda x: str(x.get("queued_at") or ""))
    return rows[-1]


def _set_queue_failure(ep: Path, item: dict, *, status: str, message: str) -> None:
    q = image_scheduler.load_queue(ep)
    target = next((x for x in q.get("items") or [] if str(x.get("id")) == str(item["id"])), None)
    if target is not None:
        target["status"] = status
        target["last_error"] = message[:1200]
        target["last_failure_at"] = image_scheduler.now()
        image_scheduler.save_queue(ep, q)


def _record_technical_failure(
    ep: Path,
    item: dict,
    *,
    token: str,
    budget_committed: bool,
    code: str,
    message: str,
) -> None:
    if not budget_committed:
        raw_candidate_budget.release(ep, token, reason=f"product_import_failure:{code}")
    image_scheduler.ledger_tech_fail(ep, item, code, message)
    _set_queue_failure(
        ep,
        item,
        status="blocked" if budget_committed else "tech_failed",
        message=f"{code}: {message}",
    )


def import_frame(ep: Path, frame: int, raw: Path, *, item_id: str | None = None, runtime: str | None = None) -> dict:
    ep = ep.resolve()
    active_runtime, _ = runtime_router.detect()
    base_runtime = str(runtime or active_runtime).upper()
    if base_runtime not in {"WORK", "WEB"}:
        raise ProductImageImportError("product image import only accepts WORK/WEB runtime evidence")
    raw = raw.resolve()
    if not valid_image(raw):
        raise ProductImageImportError(f"invalid RAW image: {raw}")
    item = find_queue_item(ep, frame, item_id)
    policy = image_model_policy.for_episode(ep)
    if str(item.get("model") or "") != str(policy["model"]):
        raise ProductImageImportError("IMAGE_MODEL_CONTRACT_MISMATCH")
    if str(item.get("quality") or "") != str(policy["quality"]):
        raise ProductImageImportError("IMAGE_QUALITY_CONTRACT_MISMATCH")
    current_contract = frame_contract.provenance(ep, frame)
    queued_contract = (item.get("frame_contract") or {}).get("contract_sha256")
    if not current_contract or str(queued_contract or "").lower() != str(current_contract["contract_sha256"]).lower():
        raise ProductImageImportError("CONTRACT_DRIFT")

    if item.get("status") != "running":
        ok, message = image_scheduler.ledger_begin(ep, item)
        if not ok:
            raise ProductImageImportError("ledger begin failed: " + message[-1200:])

    token = str(item["id"])
    budget_kind = raw_candidate_budget.kind_for_queue_item(item)
    claimed, budget_row = raw_candidate_budget.claim(
        ep,
        frame,
        budget_kind,
        reason=f"product_runtime_import runtime={base_runtime}",
        token=token,
    )
    if not claimed:
        image_scheduler.ledger_tech_fail(ep, item, "RAW_CANDIDATE_BUDGET_EXHAUSTED", str(budget_row)[:1000])
        _set_queue_failure(ep, item, status="blocked", message="RAW_CANDIDATE_BUDGET_EXHAUSTED: " + str(budget_row))
        raise ProductImageImportError("RAW_CANDIDATE_BUDGET_EXHAUSTED: " + str(budget_row))

    budget_committed = bool(budget_row.get("committed"))
    try:
        width, height, aspect = read_canvas(ep)
        stamp = int(time.time())
        raw_store = ep / "media/raw" / f"{frame:02d}-product-{stamp}{raw.suffix.lower() or '.png'}"
        raw_store.parent.mkdir(parents=True, exist_ok=True)
        raw_store.write_bytes(raw.read_bytes())
        output = ep / "media/candidates/scheduled" / f"{frame:02d}-{item['id']}-product.png"
        output.parent.mkdir(parents=True, exist_ok=True)

        receipt_info = provider_capability.write_receipt(
            ep,
            frame,
            provider_capability.inspect(
                raw_store,
                width,
                height,
                model=policy["model"],
                route=f"{base_runtime.lower()}_product_runtime_image",
                frame=frame,
            ),
        )
        try:
            norm = normalize(raw_store, output, width, height)
        except NormalizeError as exc:
            raise ProductImageImportError(f"{exc.code}: raw preserved at {raw_store}; {exc}") from exc

        receipt_path = Path(receipt_info["path"])
        if not receipt_path.is_absolute():
            receipt_path = ROOT / receipt_path
        receipt_info = provider_capability.finalize_receipt(receipt_path, norm, output)
        committed, commit_row = raw_candidate_budget.commit(
            ep,
            token,
            reason="product_runtime_normalized_candidate_exists",
        )
        if not committed:
            raise ProductImageImportError("CANDIDATE_COMMIT_FAILED: " + str(commit_row))
        budget_committed = True

        payload = {
            "ok": True,
            "backend": "product_runtime_image",
            "runtime": base_runtime,
            "frame": f"{frame:02d}",
            "raw_output": str(raw_store),
            "output": str(output),
            "target_size": [width, height],
            "aspect_ratio": aspect,
            "normalization": norm,
            "provider_receipt": {k: v for k, v in receipt_info.items() if k != "receipt"},
            "provider_capability": receipt_info.get("receipt"),
            "frame_contract": {"contract_sha256": current_contract["contract_sha256"]},
            "image_model": {
                **policy,
                "enforcement": "runtime_request_to_product_runtime_contract",
                "provider_attestation": False,
                "generation_route": "product_runtime_image",
            },
        }
        result = {"output": output, "payload": payload}
        ok, message = image_scheduler.ledger_success(ep, item, result)
        if not ok:
            raise ProductImageImportError("PRODUCT_RUNTIME_LEDGER_SUCCESS_FAILED: " + message[-1200:])

        q = image_scheduler.load_queue(ep)
        target = next((x for x in q.get("items") or [] if str(x.get("id")) == str(item["id"])), None)
        if target is not None:
            target["status"] = "generated"
            target["output_path"] = repo_rel(output)
            target["completed_at"] = image_scheduler.now()
            target["last_error"] = None
            target["product_runtime"] = base_runtime
            target["candidate_budget"] = commit_row
            image_scheduler.save_queue(ep, q)
        return payload
    except Exception as exc:
        code = "PRODUCT_RUNTIME_IMPORT_FAILED"
        if isinstance(exc, ProductImageImportError):
            text = str(exc)
            if ":" in text:
                code = text.split(":", 1)[0]
        elif isinstance(exc, NormalizeError):
            code = exc.code
        _record_technical_failure(
            ep,
            item,
            token=token,
            budget_committed=budget_committed,
            code=code,
            message=str(exc)[:1200],
        )
        if isinstance(exc, ProductImageImportError):
            raise
        raise ProductImageImportError(f"{code}: {exc}") from exc


def self_test() -> None:
    assert valid_image.__name__ == "valid_image"
    assert ProductImageImportError.__name__ == "ProductImageImportError"
    print("PRODUCT IMAGE IMPORT V2.6.1.1 SELF-TEST PASS")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("import")
    p.add_argument("episode_dir", type=Path)
    p.add_argument("--frame", required=True, type=int)
    p.add_argument("--raw", required=True, type=Path)
    p.add_argument("--item-id")
    p.add_argument("--runtime", choices=["WORK", "WEB"])
    sub.add_parser("self-test")
    args = ap.parse_args()
    if args.cmd == "self-test":
        self_test()
        return 0
    ep = args.episode_dir.resolve()
    try:
        result = import_frame(ep, args.frame, args.raw, item_id=args.item_id, runtime=args.runtime)
    except (OSError, ValueError, ProductImageImportError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False))
        return 2
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
