#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Story OS V2.7 Visual Lock evidence reconcile.

Only reconciles evidence generated by visual-lock-final-report.json.
Never edits image assets or bypasses gate validation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8-sig"))


def dump(path: Path, data):
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def reconcile(ep: Path):
    report = load(ep / "meta" / "visual-lock-final-report.json")
    if report.get("decision") != "PASS":
        raise RuntimeError("final visual lock report is not PASS")

    gates_path = ep / "meta" / "story-gates.json"
    gates = load(gates_path)

    visual = gates.setdefault("visual", {})
    calibration = visual.setdefault("calibration", {})
    items = calibration.setdefault("items", [])

    by_frame = {int(x["frame"]): x for x in items if "frame" in x}
    for frame in report.get("frames", []):
        frame_no = int(frame["frame"])
        current = by_frame.get(frame_no)
        if current is None:
            raise RuntimeError(f"missing calibration evidence frame {frame_no}")

        # visual-lock-final-report.contract_sha256 is evidence generated by the
        # finalizer. Gate validation requires the actual Resolved Frame Contract
        # SHA from runtime/contracts/frames/{frame}.json.
        contract_path = ep / "meta" / "runtime" / "contracts" / "frames" / f"{frame_no:02d}.json"
        if not contract_path.is_file():
            raise RuntimeError(f"missing frame contract: {contract_path}")
        contract = load(contract_path)
        contract_sha = contract.get("contract_sha256")
        if not contract_sha:
            raise RuntimeError(f"frame contract sha missing: {contract_path}")

        current["contract_sha256"] = frame.get("contract_sha256")
        current["frame_contract_sha256"] = contract_sha
        asset_path = frame.get("asset_path")
        if asset_path:
            asset = (ROOT / asset_path).resolve()
            if asset.is_file():
                current["sha256"] = sha256_file(asset)
                current["asset_path"] = asset_path
        current["decision"] = "passed"

    calibration["finalizer_reconciled"] = True
    calibration["finalizer_source"] = "meta/visual-lock-final-report.json"

    sheet_path = (visual.get("calibration_contact_sheet") or {}).get("path")
    if not sheet_path:
        sheet = ep / "media" / "review" / "contact-sheets" / "visual-lock-admission.jpg"
        if sheet.is_file():
            visual["calibration_contact_sheet"] = {
                "path": sheet.resolve().relative_to(ROOT.resolve()).as_posix(),
                "sha256": sha256_file(sheet),
            }

    dump(gates_path, gates)
    return {
        "result": "PASS",
        "frames": len(report.get("frames", [])),
        "source": "visual-lock-final-report.json"
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("episode_dir")
    args = ap.parse_args()
    result = reconcile(Path(args.episode_dir).resolve())
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
